### ISSUE TITLE
struct.error: unpack requires a buffer of 8 bytes when trying to extract a .closure file

### ISSUE THREAD

**Issue by gcathelain** [arandomdev/DyldExtractor#10]
Hi there, 

I found a .closure file in the dyld folder, but trying to open it leads to the following error : 

    C:\Users\default\DyldExtractor>python extractor.py -l MyApp.closure
    Traceback (most recent call last):
      File "extractor.py", line 117, in <module>
        dyldFile = Dyld.DyldFile(dyldFileHandle)
      File "C:\Users\default\DyldExtractor\DyldExtractor\Dyld\DyldFile.py", line 43, in __init__
        self.mappings.append(DyldStructs.dyld_cache_mapping_info.parse(dyldFile, mappingOff))
      File "C:\Users\default\DyldExtractor\DyldExtractor\Structure.py", line 91, in parse
        fieldValue = struct.unpack(field[1], buffer.read(fieldSize))[0]
    struct.error: unpack requires a buffer of 8 bytes

Am I missing something, or misusing your code ? 

Thanks in advance for your help

**Comment by arandomdev** [comment]
This tool is used to extract frameworks and libraries from the actual DYLD shared cache. A closure file is something that dyld uses to speed up loading...
