### ISSUE TITLE
Some unresolved C-strings in libafc.dylib iOS 14.3 arm64

### ISSUE THREAD

**Issue by PoomSmart** [arandomdev/DyldExtractor#14]
**Describe the bug**

These C-strings (`1D9712000 - 1D9712060`) are not resolved correctly as I open `libafc.dylib` extracted from your tool using IDA Pro 7.5

![image](https://user-images.githubusercontent.com/3608783/120924836-d8220380-c6ff-11eb-943b-e61df86c4ccb.png)

**To Reproduce**
1. iOS 14.3
2. arm64, let's say iPhone SE (1st gen)

**Additional context**

**Comment by arandomdev** [comment]
Thank you for bringing this up, this was fixed with bbafb3891d6c1ea7b9ea88c5472edf745c6e977c.
