### ISSUE TITLE
Extracting AVFoundation from iPhone13,2_14.1_18A8395 IPSW gives an invalid 48KB Mach-O binary

### ISSUE THREAD

**Issue by bartzy** [arandomdev/DyldExtractor#16]
**Describe the bug**
Using latest master for DyldExtractor, the extracted binary for AVFoundation is only 48KB and seems like it's not valid. 

**To Reproduce**
1. iPhone13,2_14.1_18A8395 IPSW
3. python extractor.py -f AVFoundation path_to_dyld_shared_cache_arm64e

I'm probably doing something wrong here?

**Comment by arandomdev** [comment]
What do you mean by not valid? The extracted files are not executable.

**Comment by bartzy** [comment]
is 48KB valid for the entire AVFoundation framework? I'm trying to read it with Hopper and getting almost nothing as Objective-C labels etc.

**Comment by arandomdev** [comment]
Ah, you're probably using arm64e. The current version of DyldExtractor fails horrendously on arm64e. Until the next version of the extractor is out, I suggest that you use an arm64 cache.

**Comment by bartzy** [comment]
Ah, that must be it. Thanks!
so arm64 is from iPhone X and below if I'm understanding correctly?

**Comment by arandomdev** [comment]
Yep

**Comment by bartzy** [comment]
Thanks!

**Comment by bartzy** [comment]
@arandomdev Still getting the same 48KB file (and same `Can't get selrefs section` error) with the following IPSW: iPhone10,3,iPhone10,6_14.6_18F72 (iPhone X 14.6).
Any idea?

**Comment by arandomdev** [comment]
Ok, I tried to extract AVFoundation with the new extractor and I also got a file that around 48KB. Looking at it with Ghidra, the file seems to be some sort of middle man between apps that depend on it and the actual code for the AVFoundation framework. In Hopper, if you look at the MachO header, you should see some dependencies like AVFAudio and AVFCore. Try looking at those instead.

**Comment by bartzy** [comment]
@arandomdev Yep, that's it. AVFCore is what I was looking for and I just didn't realize that. Sorry for the trouble and thanks again.

**Comment by arandomdev** [comment]
no problem!
