### ISSUE TITLE
Case-sensitive Python imports

### ISSUE THREAD

**Issue by PoomSmart** [arandomdev/DyldExtractor#18]
**Describe the bug**

<img width="970" alt="image" src="https://user-images.githubusercontent.com/3608783/124342647-85991180-dbef-11eb-8e78-31d1157ba036.png">

Given these imports, for examples:
```
from DyldExtractor.dyld.dyld_context import DyldContext
from DyldExtractor.macho.macho_context import MachOContext
```

Due to the fact the dyld and macho directories are actually Dyld and MachO, imports won't be resolved correctly and make running scripts impossible.

This occurs at least with Python 3.9.5 on macOS.

There are two possible solutions:

1. Rename the directories `Dyld` to `dyld`, `MachO` to `macho` and `Converter` to `converter`.
2. Replace every occurrence of `dyld`,`macho` and `converter` in imports with `Dyld`, `MachO` and `Converter`, respectively.

**Comment by arandomdev** [comment]
Oh sorry I ran into this issue before. Because git doesn’t keep track of folder case changes, when you pulled the latest version it didn’t rename it. Can you delete DyldExtractor and clone it again? Alternatively you can do 1 from your suggestions.

**Comment by PoomSmart** [comment]
It's okay. By the way, if you do `git mv` the changes should reflect.

**Comment by arandomdev** [comment]
Thanks for letting me know!
