### ISSUE TITLE
Invalid address in CameraUI framework of iOS 14.6

### ISSUE THREAD

**Issue by PoomSmart** [arandomdev/DyldExtractor#21]
**Describe the bug**

Inside method `-[CAMStillImageCaptureCommand executeWithContext:]` of `CameraUI` private framework, there is an invalid address referenced at `1A8AAF004` and `1A8AAF010`. You should be able to reproduce this on every iOS 14.6 dyld shared cache.

![image](https://user-images.githubusercontent.com/3608783/130343479-995ac7bf-701b-43ee-b1cc-2ac23f705e89.png)

**To Reproduce**
1. iOS 14.6
2. iPhone X

**Additional context**

**Comment by arandomdev** [comment]
I’ll look at it but please provide both the image you’re trying to extract, and the exact version of the cache you’re using by ipsw.me

**Comment by PoomSmart** [comment]
@arandomdev Try https://ipsw.me/download/iPhone10,6/18F72

**Comment by arandomdev** [comment]
Okay, I think I fixed it in 39d6d91, you can install it with `pip install git+https://github.com/arandomdev/DyldExtractor.git`. Let me know if it works and if there are any regressions.

**Comment by PoomSmart** [comment]
@arandomdev It doesn't seem to be fixed. Note that this is IDA Pro 7.6 SP1
![image](https://user-images.githubusercontent.com/3608783/130460609-b7da7c46-b1e3-4b8d-a810-56574adcb1cd.png)

**Comment by arandomdev** [comment]
Maybe try uninstalling and reinstalling with the command above?

**Comment by PoomSmart** [comment]
@arandomdev That fixes it. Great job. 👍🏻 

![image](https://user-images.githubusercontent.com/3608783/130547525-d93b62d2-2312-4241-80b5-b15dfc8f9f7e.png)

**Comment by arandomdev** [comment]
The fix was rolled back with 15553dc34c51ef55099fbeb4bcd085bdf622ec14

**Comment by arandomdev** [comment]
okay, I think I finally fixed it with ac28f8db4414e772559b388c4c896077605276d9
