### ISSUE TITLE
Invalid address in Celestial framework iOS 14.6

### ISSUE THREAD

**Issue by PoomSmart** [arandomdev/DyldExtractor#24]
**Describe the bug**

Invalid addresses in `Celestial.framework`, a private framework in iOS 14.6 dyld shared cache.

Example method: `+[FigCheckpointSupport makeDictionary]` at `19CB08A48` and `19CB08A54`, the invalid address is `0x1CBCCEDB3`.

![image](https://user-images.githubusercontent.com/3608783/130606644-5781855b-be99-4406-834a-d92bb1d22edb.png)

**To Reproduce**
1. iOS 14.6
2. DYLD target device and identifier: https://ipsw.me/download/iPhone10,6/18F72
3. DyldExtractor 1.0.1

**Comment by arandomdev** [comment]
This seems to be the same issue with #21, unfortunately, the fix for that issue introduced some more bugs and doesn't work really well. I'm going to roll that commit back and come up with a better solution.

**Comment by PoomSmart** [comment]
@arandomdev Still an issue in 1.0.2, same context.

![image](https://user-images.githubusercontent.com/3608783/132228634-7ae1acf6-8aa5-4f48-84f5-c8d7ea7791ea.png)

**Comment by arandomdev** [comment]
Have you tried uninstalling and reinstalling it?

**Comment by PoomSmart** [comment]
@arandomdev yes, uninstalled and reinstalled. Does this binary work for you?

**Comment by arandomdev** [comment]
Oh yes I see now, should have paid more attention.

I’ll see what I can do

**Comment by arandomdev** [comment]
okay finally fixed with ea29a8ee9055e2821122ae90bddcb9c865ea0f7f
