### ISSUE TITLE
Invalid address in Celestial framework iOS 14.6

### ISSUE THREAD

**Issue by PoomSmart** [arandomdev/DyldExtractor#25]
**Describe the bug**

`Celestial.framework`, a private framework in iOS 14.6 dyld shared cache.

Inside method: `+[FigCheckpointSupport makeDictionary]`, the bad address is `0x1CC78D8FB`.

![image](https://user-images.githubusercontent.com/3608783/132974093-40cfb85f-6c84-4893-8b4d-6884396a622b.png)

**To Reproduce**
1. iOS 14.6
2. DYLD target device and identifier: https://ipsw.me/download/iPhone10,6/18F72
3. DyldExtractor 1.0.3

**Comment by arandomdev** [comment]
Dang, this is a really tough issue. Usually, the ADRP and ADD instructions are right next to each other, but in this case they're randomly far away... I'll see what I can do.

**Comment by arandomdev** [comment]
I completely changed the way that selector references are found with af5d4b0d3c9330c1595bd0bd9f22f1b765478afd. I think the output is actually much better now...

I put it into a new branch in case of regressions but can you test it and let me know how it goes?

**Comment by Ellitvin115** [comment]
> **Describe the bug**
> 
> `Celestial.framework`, a private framework in iOS 14.6 dyld shared cache.
> 
> Inside method: `+[FigCheckpointSupport makeDictionary]`, the bad address is `0x1CC78D8FB`.
> 
> ![image](https://user-images.githubusercontent.com/3608783/132974093-40cfb85f-6c84-4893-8b4d-6884396a622b.png)
> 
> **To Reproduce**
> 
> 1. iOS 14.6
> 2. DYLD target device and identifier: https://ipsw.me/download/iPhone10,6/18F72
> 3. DyldExtractor 1.0.3

**Comment by PoomSmart** [comment]
@arandomdev No adverse effects so far. Great work. 👍🏻

**Comment by arandomdev** [comment]
Merged onto master with 0c119505d62c42eaefec608bcab64fdb5bdf383e
