### ISSUE TITLE
Invalid addresses in CameraUI framework iOS 14.6

### ISSUE THREAD

**Issue by PoomSmart** [arandomdev/DyldExtractor#27]
**Describe the bug**

Inside the method `-[CAMViewfinderViewController _nextResolutionVideoConfigurationForVideoConfiguration:]`, wrong addresses appear at `1A8B1A52C` and `1A8B1A53C`.

![image](https://user-images.githubusercontent.com/3608783/136643887-1b73b1c9-e65f-4c1f-a4dc-7cb51e76d77d.png)

For the same method, this address at `1A8B1A5AC` is not invalid, but is most likely incorrect (`0x1CBCCE000`).

![image](https://user-images.githubusercontent.com/3608783/136643915-fb88b104-73cf-4f76-9ee4-e1dcb0fc56ba.png)

**To Reproduce**
1. iOS version 14.6
2. DYLD target device and identifier https://ipsw.me/download/iPhone10,6/18F72
3. DyldExtractor 1.0.4

**Additional context**

**Comment by arandomdev** [comment]
I think I fixed this with ce99c9dbd5dd5e50b55f03190ae34b42f0cd89d1, and version 1.0.5 on pypi.
