### ISSUE TITLE
AppleDisplay DarwinOS 15.4, unknown local symbol entries struct

### ISSUE THREAD

**Issue by asdfugil** [arandomdev/DyldExtractor#36]
**Describe the bug**
Nothing shows up in binaries after extraction

**To Reproduce**
1. DarwinOS version: 15.4
2. DYLD target device and identifier: AppleDisplay2,1
3. `dyldex_all dyld_shared_cache_arm64e`
4. Nothing in binaries

**Additional context**
[OTA firmware download, which contains the RootFS](https://updates.cdn-apple.com/2022FCSWinter/patches/694-34933/73C7763D-6DB5-42D9-8B84-F22DCAF6ECB6/com_apple_MobileAsset_DarwinAccessoryUpdate_A2525/48013376924d2561a862d49a48085a02f6359496.zip)

**Comment by arandomdev** [comment]
I think I fixed it with 972df96, please try it out and let me know how it goes.
You can update with `pip install git+https://github.com/arandomdev/DyldExtractor.git`.

**Comment by asdfugil** [comment]
Got a lot of `[ WARNING ] stub_fixer.py:174 : Unable to find dependency: SOME PATH` but ok it extracted

**Comment by arandomdev** [comment]
I think it’s because those dependencies are on the disk instead of in the cache, but as long as it isn’t accompanied by any other errors, especially in stub fixer, it should be fine.

I’ll close this issue when I upload a new package to pypi.

**Comment by arandomdev** [comment]
Uploaded to pypi with version bump, 0fb102e.
