### ISSUE TITLE
Extract nothing from iOS 14 arm64 cache file

### ISSUE THREAD

**Issue by YiYiZheng** [arandomdev/DyldExtractor#37]
**Describe the bug**
Extract nothing from iOS 14 arm64 cache file

**To Reproduce**
1. iOS version  14.2
2. DYLD target device and identifier iPhone SE  iPhone8,4
3. Terminal command to reproduce: dyldex_all dyld_shared_cache_arm64  

**Additional context**
Log:
- |#                                                  | 0 Elapsed Time: 0:00:00

----- Summary -----

-------------------

**Comment by arandomdev** [comment]
Hmm, that's weird, it seems to work for me. Are you on the latest version, 2.0.3?

**Comment by YiYiZheng** [comment]
> Hmm, that's weird, it seems to work for me. Are you on the latest version, 2.0.3?

YES, it's 2.0.3. And I get the cache file from

![image](https://user-images.githubusercontent.com/43005999/161360618-c7835bb9-c127-4326-93b7-9d639e6badaa.png)

Can you try my cache file? I could send it to you by email

**Comment by arandomdev** [comment]
Sure, you can zip it and send it to haow6449@gmail.com.
If it's too big, you can give me a download link.

**Comment by YiYiZheng** [comment]
> 

Already send an email to you, Thx

**Comment by arandomdev** [comment]
Okay I got your file. It seems that the file is broken or not a cache.
On a normal cache, there should be a `magic` at the beginning, but your cache doesn't have it. For example,
![image](https://user-images.githubusercontent.com/40927866/161361986-2cb17d46-53c6-4eac-93ce-3ab512a48bb0.png)
![image](https://user-images.githubusercontent.com/40927866/161361997-60504979-906d-425b-b4a0-f70dfb277926.png)

I don't know how you get your file, but in regards to DyldExtractor, I might add a check for the `magic`.

**Comment by YiYiZheng** [comment]
> Okay I got your file. It seems that the file is broken or not a cache. On a normal cache, there should be a `magic` at the beginning, but your cache doesn't have it. For example, ![image](https://user-images.githubusercontent.com/40927866/161361986-2cb17d46-53c6-4eac-93ce-3ab512a48bb0.png) ![image](https://user-images.githubusercontent.com/40927866/161361997-60504979-906d-425b-b4a0-f70dfb277926.png)
> 
> I don't know how you get your file, but in regards to DyldExtractor, I might add a check for the `magic`.

I got from this directory by iFunBox
https://user-images.githubusercontent.com/43005999/161360618-c7835bb9-c127-4326-93b7-9d639e6badaa.png

**Comment by arandomdev** [comment]
Can you use `scp` to copy it from the device? I usually download the ipsw and get it from there.

**Comment by YiYiZheng** [comment]
> Can you use `scp` to copy it from the device? I usually download the ipsw and get it from there.

Solved!  It works by using scp. Thx!

**Comment by arandomdev** [comment]
I'll close this issue now that I added a check with 78b56ea.
