### ISSUE TITLE
symbolicating the __objc_classrefs and __objc_superrefs sections

### ISSUE THREAD

**Issue by fabianfreyer** [arandomdev/DyldExtractor#38]
**Describe the bug**
currently, the pointers in the `__objc_classrefs` and `__objc_superrefs` sections point outside of the mapped address space of the binary to class objects in other images within the dsc. In many cases, they have symbols exported by the other images. It would be great if they could be fixed up somehow as well, e.g. by creating a fake section with the corresponding symbols or importing them somehow.

**To Reproduce**
1. iOS version 15.4
2. DYLD target device and identifier, i.e iPhone10,4
3. Extract any library and look at the `__objc_classrefs` and `__objc_superrefs` section

**Additional context**
It looks like this in Binary Ninja: The entries without a symbol point outside the Mach-O and don't have a symbol.
<img width="783" alt="image" src="https://user-images.githubusercontent.com/3423837/165878282-a543446c-f4ad-4936-843f-835928b80946.png">

**Comment by arandomdev** [comment]
Okay I added processing for `__objc_protorefs`, `__objc_classrefs`, and `__objc_superrefs` with 8290c86, and 2.0.7 on pypi.

**Comment by fabianfreyer** [comment]
Thanks!
