### ISSUE TITLE
iOS16 changed somethings again 😩

### ISSUE THREAD

**Issue by blacktop** [arandomdev/DyldExtractor#41]
macOS DSC seem to be the same as they were, but iOS has like 42 splits/sub_caches now as well as `.dylddata` and `.dyldlinkedit` files.

I have updated my Dyld.bt [here](https://github.com/blacktop/ipsw/commit/127eec868ca65e09d63640e646f3cc3bacae0d7f#diff-9004dba818e2395cf011ab71a669399340819c05613a352006ce032b1fc33dc3)

I was getting good ObjC runtime info parsing, but I think GOT and stubs are different?

**Comment by blacktop** [comment]
I think they are using `cacheType` of 2 to signify this NEW cach type.  macOS beta is 0 *(CacheTypeDevelopment)*.

**Comment by blacktop** [comment]
### Here's the OLD dsc
![old_dyld](https://user-images.githubusercontent.com/6118188/172286749-681a6715-e90b-470c-9eda-04ecd2a5d66b.png)
### And the NEW dsc
![new_dyld](https://user-images.githubusercontent.com/6118188/172286800-e2dc4856-78f7-41b7-87ce-057708b72e2d.png)

> **Note**
> I'm failing to lookup the GOT syms

**Comment by blacktop** [comment]
So I added the NEW fields to the Dyld.bt, essentially so far just more fields in the subCacheInfo struct, looks like a LOT of info as to what the subcache contains and what address or fileoffset it will be at.  Prob a gold mine, haven't finished my analysis of it yet.
So I do the same order (symbols meaning locals/privates right?) and then I walk the GOTs and stubs and look those up, so I think that means that the stubs are pointing to something outside the dylibs boundaries, see the error in the second disassembly: `address BLAH not in any dylib` that was `ipsw` trying to symbolicate the stubs

**Comment by arandomdev** [comment]
hmm weird, I'm spinning up a VM in order to extract the caches (apfs-fuse isn't working for me), but I'll let you know if I find something.

**Comment by blacktop** [comment]
apfs-fuse in my `ipsw` docker container?  I recently had to update `ipsw` to work w/ these new caches because they now live in their own DMG, the Cryptex1,SystemOS dmg, just FYI.

**Comment by blacktop** [comment]
ah ok

**Comment by blacktop** [comment]
> So I added the NEW fields to the Dyld.bt, essentially so far just more fields in the subCacheInfo struct, looks like a LOT of info as to what the subcache contains and what address or fileoffset it will be at. Prob a gold mine, haven't finished my analysis of it yet. So I do the same order (symbols meaning locals/privates right?) and then I walk the GOTs and stubs and look those up, so I think that means that the stubs are pointing to something outside the dylibs boundaries, see the error in the second disassembly: `address BLAH not in any dylib` that was `ipsw` trying to symbolicate the stubs/or GOT auth ptrs

turns out it is NOT a gold mine of addr info, in fact it's char [32] containing the sub cache's extension. 🤦

**Comment by arandomdev** [comment]
It's ok 😊. I finally got a VM up (after 2 whole days), and should be able to look at it soon. Thanks for the info!

**Comment by arandomdev** [comment]
After fixing a few small issues, I was able to get DyldExtractor working, even without modification to my stub fixer.
![image](https://user-images.githubusercontent.com/40927866/172741544-b929041d-7b01-414e-a2d3-51ee35277fc2.png)

Interesting note though, there seems to be special stubs specifically for certain `objc_msgSend`.

**Comment by arandomdev** [comment]
Oh and are you using indirect symbols for symbol pointers? https://github.com/arandomdev/DyldExtractor/blob/8290c86914008abae24be6a78677f15bc4df979c/src/DyldExtractor/converter/stub_fixer.py#L1034

**Comment by blacktop** [comment]
> After fixing a few small issues, I was able to get DyldExtractor working, even without modification to my stub fixer. ![image](https://user-images.githubusercontent.com/40927866/172741544-b929041d-7b01-414e-a2d3-51ee35277fc2.png)
> 
> Interesting note though, there seems to be special stubs specifically for certain `objc_msgSend`.

that's awesome!

**Comment by blacktop** [comment]
So for that last bl in NSLog that was what that addr is not in any dylib error was, and when I use XCode to split and look at it in binja:
<img width="668" alt="Screen Shot 2022-06-08 at 11 08 30 PM" src="https://user-images.githubusercontent.com/6118188/172768927-7064569b-8e44-4926-ac41-fdd1fa5550be.png">

**Comment by blacktop** [comment]
> 

I believe so:

I check the:
ExportTrie
symtab
LC_DYLD_INFO binds/exports
locals
objc class/meth/sels etc

then use that to lookup stubs/gots symbols from their ptrs/stub immediates etc

**Comment by blacktop** [comment]
> So for that last bl in NSLog that was what that addr is not in any dylib error was, and when I use XCode to split and look at it in binja: <img alt="Screen Shot 2022-06-08 at 11 08 30 PM" width="668" src="https://user-images.githubusercontent.com/6118188/172768927-7064569b-8e44-4926-ac41-fdd1fa5550be.png">

so this address just points to a "stub island" that is in the space between dylibs??

either that or I have a bug in my "what dylib contains this address code"?

**Comment by blacktop** [comment]
So when I look for stubs etc I always look in the boundaries of a dylib, but if you designed dyldex from the start to look in the entire cache I could see how this didn't break you at all.

**Comment by arandomdev** [comment]
Yep, I did some more digging, and it seems that the branch above branches to a region in cache .02 which contains a continuous range of stub trampolines, which then branches to the actual `___stack_chk_fail`.

I also found out that DyldExtractor doesn't fix the pointer for ___stack_chk_guard, but that might be a scoped for DyldExtractorC.

**Comment by arandomdev** [comment]
I didn't look too closely but you may need to recursively resolve the branch to a stub until you hit a function before you can symbolize it.
https://github.com/arandomdev/DyldExtractor/blob/8290c86914008abae24be6a78677f15bc4df979c/src/DyldExtractor/converter/stub_fixer.py#L408
https://github.com/arandomdev/DyldExtractor/blob/8290c86914008abae24be6a78677f15bc4df979c/src/DyldExtractor/converter/stub_fixer.py#L1441

**Comment by arandomdev** [comment]
This commit should close this issue, 70c99eed9bccaf0c8c7b46f40ced51f52fa3f69a.
