### ISSUE TITLE
DyldContext attempts to open .symbols file without checks.

### ISSUE THREAD

**Issue by santalvarez** [arandomdev/DyldExtractor#45]
Hi, Im on macOS 12 (Monterey) and I am getting an error when trying to extract the cache.
```
FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/dyld/dyld_shared_cache_x86_64.symbols'
```

The file shown in the error does indeed not exist, does this mean DyldExtractor doesn't work in macOS 12?

**Comment by arandomdev** [comment]
DyldExtractor does not support x86_64 caches, but the error that is shown should have not happened. If possible, can you send me a file with the first 512 bytes of the main cache, `/System/Library/dyld/dyld_shared_cache_x86_64`.
You can use the following command, `dd count=1 if=INPUT_FILE of=OUTPUT_FILE`.

**Comment by santalvarez** [comment]
Yeah, here you go
[dyld_shared_cache_x86_64.zip](https://github.com/arandomdev/DyldExtractor/files/9439869/dyld_shared_cache_x86_64.zip)

**Comment by arandomdev** [comment]
Okay, I added a small check with [934b17d](https://github.com/arandomdev/DyldExtractor/commit/934b17d34b24a0ec3669092535a5bd808163ae4f).
As for x86_64 support, [DyldExtractorC](https://github.com/arandomdev/DyldExtractorC) will support it, but development is going really slow unfortunately.

**Comment by santalvarez** [comment]
Nice, thank you. I tried it and I am getting this error for every lib, even in arm64e.

```
Processed: libsystem_info.dylib
----- libsystem_info.dylib -----
12:19:02:511 [  ERROR  ] dyldex_all:184 : 'NoneType' object has no attribute 'header'
Traceback (most recent call last):
  File "/usr/local/bin/dyldex_all", line 159, in _extractImage
    linkedit_optimizer.optimizeLinkedit(extractionCtx)
  File "/usr/local/lib/python3.9/site-packages/DyldExtractor/converter/linkedit_optimizer.py", line 600, in optimizeLinkedit
    optimizer.copyLocalSymbols(newLinkedit)
  File "/usr/local/lib/python3.9/site-packages/DyldExtractor/converter/linkedit_optimizer.py", line 270, in copyLocalSymbols
    if symbolsCache.header.localSymbolsOffset == 0:
AttributeError: 'NoneType' object has no attribute 'header'
--------------------
```

**Comment by arandomdev** [comment]
Hmm I probably should have done more testing, can you send me a download link for your cache files so I can look deeper into the issue?

**Comment by torarnv** [comment]
Also seeing this for an x86_64h cache

**Comment by arandomdev** [comment]
If possible can you send me your cache files? It would very helpful.

**Comment by torarnv** [comment]
Do you have an email I can reach you on?

**Comment by arandomdev** [comment]
Yep, haow6449@gmail.com

**Comment by arandomdev** [comment]
I added another check with 7a559b60a141323da11ce6d94e1ab1445b0d1a17 and that seems to fix this issue, but x86_64h still fails in ObjC Fixer.
