### ISSUE TITLE
iOS 12.5.6 (16H71) : stub_fixer warning 

### ISSUE THREAD

**Issue by ahmed24khaled** [arandomdev/DyldExtractor#46]
Hello,

I'm trying to extract all binaries for iOS 12.5.6 (16H71) arm64, but I got several warnings (2783 binaries concerned) as below:

```
----- libswiftWatchKit.dylib -----18:39:57:457 [ WARNING ] stub_fixer.py:1155 : Unable to symbolize pointer at 0x1b80c1e28, with indirect entry index 0x15, with target function 0x0

----- libswiftCore.dylib -----18:39:55:505 [ WARNING ] stub_fixer.py:1155 : Unable to symbolize pointer at 0x1b8094418, with indirect entry index 0xd3, with target function 0x0

----- UIKitCore -----18:39:54:667 [ WARNING ] stub_fixer.py:1155 : Unable to symbolize pointer at 0x1b7b4f440, with indirect entry index 0x77e, with target function 0x0
```

What does this mean and what is the impact on the extracted binaries ?

I want to use these binaries for crash symbolication.

Thank you.

**Comment by arandomdev** [comment]
It's not able to find what the pointer is trying to point to, but if you're just using it for crash symbolication, it should be fine.

**Comment by ahmed24khaled** [comment]
Thank you for your quick answer.
One more question please, on which use case this warning has an impact impact ?

**Comment by arandomdev** [comment]
worst case scenario would be reverse engineering a binary. But most of the time, it's like the dyld binder or something.

**Comment by ahmed24khaled** [comment]
got it thank you so much.
