### ISSUE TITLE
Cache's magic does not start with 'dyld', most likely given a file that's not a cache or the file is broken.

### ISSUE THREAD

**Issue by zy364601065** [arandomdev/DyldExtractor#47]
system % dyldex_all dyld_shared_cache_arm64e
Traceback (most recent call last):
  File "/usr/local/bin/dyldex_all", line 299, in <module>
    _main()
  File "/usr/local/bin/dyldex_all", line 228, in _main
    dyldCtx = DyldContext(f)
  File "/usr/local/lib/python3.10/site-packages/DyldExtractor/dyld/dyld_context.py", line 36, in __init__
    raise ValueError("Cache's magic does not start with 'dyld', most likely given a file that's not a cache or the file is broken.")  # noqa
ValueError: Cache's magic does not start with 'dyld', most likely given a file that's not a cache or the file is broken.

**Comment by arandomdev** [comment]
Where did you get the cache file from?

**Comment by zy364601065** [comment]
Get from /System/Library/Caches/com.apple.dyld/

**Comment by arandomdev** [comment]
It says that it's probably broken, are you able to open the cache file in a hex editor and tell me what the first few bytes are? It should be like something [here](https://github.com/arandomdev/DyldExtractor/issues/37#issuecomment-1086500831), where the first 4 are `dyld`.

If not, can you send the file to me? My email is haow6449@gmail.com.

**Comment by zy364601065** [comment]
I will send the document to you. Thank you for your reply

**Comment by arandomdev** [comment]
Okay, I looked at your file, and it seems that the first 0x2c580 bytes are all zeros, which is not correct.
I don't know how you got your file, but I suggest using SCP if you have a jail broken phone, or directly extracting it from an IPSW. https://github.com/blacktop/ipsw.
